---
- hosts: client1
  become: true
  tasks:
  - name: Vérification de la connexion
    ping:
  - name: Installation apache
    apt:
      name: apache2
      state: latest
      update_cache: yes
  - name: modif page d'accueuil
    copy:
      src: /home/ansible/files/J1/index.html
      dest: /var/www/html/index.html
  - name: Gestion du service
    service:
      name: apache2
      state: started
      enabled: yes

