---
- hosts: client2
  become: true
  vars:
    mysql_bind_address: 10.10.10.4
    mysql_users:
      pepito:
        priv: '*.*:ALL'
        host: '10.10.10.2'
        password: 'azerty'

  tasks:
  - name: Verification de la connexion
    ping:

  - name: installation package serveur MySQL [mysql-server]
    apt:
      name: mysql-server
      state: latest
      update_cache: yes

  - name: Installation package python3-mysqldb
    apt:
      name: python3-mysqldb
      state: latest

  - name: Autorisation connexions a distance 
    lineinfile:
      path: /etc/mysql/mysql.conf.d/mysqld.cnf
      regexp:   '^bind-address'
      line: "bind-address = {{ mysql_bind_address }}"
    notify:
      - Relancement du service mysql

  - name: Gestion du service mysql
    service:
      name: mysql
      state: started
      enabled: yes
  - name: Creation de l utilisateur MySQL
    mysql_user:
      state: present
      name: "{{ item.key }}"
      host: "{{ item.value.host }}"
      password: "{{ item.value.password }}"
      priv: "{{ item.value.priv }}"
    loop: "{{ query('dict', mysql_users) }}"

  handlers:
  - name: Relancement du service mysql
    service:
      name: mysql
      state: restarted
