---
- name: installation packages openjdk-8-jdk [openjdk-8-jdk]
  apt: 
    name: "{{ jdk_packages }}"
    state: latest
    update_cache: yes

- name: Creation utilisateur nexus
  user: 
    name: nexus

- name: Creation du repertoire /opt/nexus
  file:
    path: /opt/nexus
    state: directory

- name: Télécharger et extraire un fichier
  unarchive:
    src: http://download.sonatype.com/nexus/3/nexus-3.35.0-02-unix.tar.gz
    dest: /opt/nexus
    remote_src: yes
    creates: /opt/nexus/nexus-3.35.0-02/

- name: Modification du fichier nexus-3.35.0-02/bin/nexus.rc
  ansible.builtin.copy:
    dest: /opt/nexus/nexus-3.35.0-02/bin/nexus.rc
    content: 'run_as_user="nexus"'

- name: Donner les droits du dossier à l'utilisateur nexus
  file:
    path: /opt/nexus
    state: directory
    recurse: yes
    owner: nexus
    group: nexus

- name: Creation du lien symbolique
  file:
    src: /opt/nexus/nexus-3.35.0-02/bin/nexus
    dest: /etc/init.d/nexus 
    owner: nexus
    group: nexus
    state: link
    
- name: Lancement du service
  systemd:
    name: nexus
    state: started
    daemon_reload: yes
