---
- name: Vérification de la connexion
  ping:
- name: installation packages serveur MySQL [mysql-server,python-mysqldb]
  apt:
    name: "{{ mysql_packages }}"
    state: latest
    update_cache: yes
- name: Autorisation connexions à distance
  lineinfile:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp:   '^bind-address'
    line: "bind-address = {{ mysql_bind_address }}"
  notify:
    - Relancement du service mysql
- name: Gestion du service mysql
  service:
    name: mysql
    state: started
    enabled: yes
- name: Création de l utilisateur boby
  mysql_user:
    state: present
    name: "{{ item.key }}"
    host: "{{ item.value.host }}"
    password: "{{ item.value.password }}"
    priv: "{{ item.value.priv }}"
  loop: "{{ query('dict', mysql_users) }}"
- name: Récupération MySQL Version
  shell: mysql --version | awk '{print $5}' | awk 'gsub(",","")'
  register: mysql_version
  changed_when: False
- name: Affichage version MySQL
  debug:
    msg: "{{ mysql_version.stdout }}"
